### ISSUE TITLE
Document interacting via non std IOs to do programmatic usage

### ISSUE THREAD

**Issue by geemus** [heroku/rendezvous.rb#1]

**Comment by apsoto** [comment]
+1

I've played with it a little, but no luck.  Any sample code available on the net?  Or somewhere in heroku support knowledge base?

**Comment by geemus** [comment]
Unfortunately, I've ended up in a similar boat (so far anyway). Which is to say, I tried to get this working and had pretty mixed luck at best. Might be worth discussing and sharing efforts to try and figure out a way forward (if there is one). I recall it being tricky to figure out and debug...

**Comment by apsoto** [comment]
Hey There,

I did finally figure it out.  Here's some sample/psuedo code.  The key things I thought were:
- Provide an IO object for input because in my particular case I needed it to not mess with my STDIN.
- Similar to above, use a StringIO for the output so I can log the output where I wanted to instead of STDOUT.
- wrapped it in a thread so it wouldn't block my main thread since it does blocking IO.
- Don't forget to `#rewind` the output object

```
Thread.new do
  begin
    rz = Rendezvous.new({input:StringIO.new, output:StringIO.new, url: dyno['attach_url'], activity_timeout:300})
    rz.start
    rz.output.rewind
    log.debug("#{dyno['name']} Results:#{rz.output.readlines.join}")
  rescue => e
    log.error("Error capturing output for dyno #{dyno['name']}\n#{e.message}")
  end
  
  log.debug("completed capturing output for #{dyno['name']}")
end
```

By the way, I looked through the source of the heroku ruby client and they don't use this gem.  They basically have a copy of the Rendezvous class.  It looked almost identical to me:

https://github.com/heroku/heroku/blob/master/lib/heroku/client/rendezvous.rb

**Comment by geemus** [comment]
Yeah, I think the thread wrapping portion is what caught me before. I tried a few related things and couldn't ever quite get it to play nice (without blocking). Overall that looks good, perhaps we should add something to that effect to the README now?

Yeah, the heroku ruby client/toolbelt had the original code. I extracted it to here so that I could more easily use it in isolation. At which point I suppose we could have started using this version and removed it from the toolbelt, but I sort of forgot to close the loop in that way. I'll bring it up with the current maintainer as an option though.

**Comment by apsoto** [comment]
adding to the README can't hurt.

**Comment by geemus** [comment]
Indeed. Did you want to take a stab at that? Thanks!

**Comment by apsoto** [comment]
Sure.

**Comment by geemus** [comment]
Awesome, thanks!
